#!/usr/bin/env bash
#
# wrapper for Chrome to support user profiles and "app" windows

base="$(basename -- "$0")"
profile="${base#*-}"
cmd="${base%%-*}"

# support multiple profiles (eg. work vs personal)
if [[ "${cmd}" == "${profile}" ]] ; then
  profile="Chrome"
else
  profile="Chrome-${profile^}" # camel case
fi
dataDir="$HOME/Library/Application Support/Google/${profile}/"

# support "app" mode via symlinks and cmdline args
case "${cmd}" in
  chrome)
    args="$@"
    ;;
  g*)
    args="--app=https://${cmd#?}.google.com/"
    ;;
  outlook)
    args="--app=https://outlook.office365.com/mail/inbox"
    ;;
  ocal)
    args="--app=https://outlook.office365.com/calendar/view/workweek"
    ;;
  *)
    if [[ -n "$1" ]] ; then
      args="--app=$@"
    else
      args="--app=https://${cmd}.com/"
    fi
    ;;
esac

open -n -a "Google Chrome" --args --user-data-dir="${dataDir}" ${args}
