#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "NeoSolarized"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    # vimcompatible = true 
    #filemanager = "nerdtree"
    bootstrap_before = 'deekue#before'
    bootstrap_after = 'deekue#after'

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'lang#dockerfile'

[[layers]]
name = 'lang#go'

#[[layers]]
#name = 'lang#groovy'

[[layers]]
name = 'lang#java'
# brew install google-java-format
java_formatter_jar = '/usr/local/var/homebrew/linked/google-java-format/libexec/google-java-format.jar'

[[layers]]
name = 'lang#kotlin'

[[layers]]
name = 'lang#python'
enabled_linters = ['python', 'pylint']

[[layers]]
name = 'lang#typescript'
#typescript_server_path = ''
# yarn add -D lehre
#lehre_path = ''

[[layers]]
name = 'lang#javascript'
#auto_fix = true
#enable_flow_syntax = true
#format_on_save = true

[[layers]]
name = 'lsp'
filetypes = [
    'dockerfile',
    'go',
    'java',
    'kotlin',
    'python',
  ]
enabled_clients = ['pylsp']
[layers.override_cmd]
  dockerfile = ["lsp-dockerfile.sh"]
  go = ["gopls"]
  java = ["lsp-java.sh"]
  kotlin = ["lsp-kotlin.sh"]

[[layers]]
name = 'VersionControl'

[[layers]]
name = 'colorscheme'

[[layers]]
name = 'git'
git-plugin = 'fugitive'

[[layers]]
name = 'github'

[[layers]]
name = "ui"
enable_sidebar = true

[[layers]]
#name = "unite"
#name = "denite"
name = "fzf"

[[layers]]
name = "tmux"
tmux_navigator_modifier = "alt"

[[custom_plugins]]
name = "aliou/bats.vim"
merged = false

[[custom_plugins]]
name = "tpope/vim-projectionist"

[[custom_plugins]]
name = "mickael-menu/zk-nvim"
merged = false

